language: ruby
rvm:
  - 2.6.3
before_script:
  - bundle exec rails db:setup
script:
  - bundle exec rake
services:
  - postgresql
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
